/** @type {import('jest').Config} */
module.exports = {
  moduleFileExtensions: ['js', 'json', 'ts'],
  rootDir: '.',
  testRegex: '.*\\.(spec|integration-spec)\\.ts$',
  transform: {
    '^.+\\.(t|j)s$': 'ts-jest',
  },
  collectCoverageFrom: [
    'apps/**/*.(t|j)s',
    'libs/**/*.(t|j)s',
    '!**/*.spec.ts',
    '!**/*.integration-spec.ts',
    '!**/node_modules/**',
    '!**/dist/**',
    '!**/main.ts',
    '!**/app.module.ts',
    '!**/*.module.ts',
    '!**/*.config.ts',
    '!**/prisma.config.ts',
    '!**/dto/**',
    '!**/interfaces/**',
    '!**/enums/**',
    '!**/events/*.ts',
    '!libs/shared/src/index.ts',
  ],
  coverageDirectory: './coverage',
  coverageProvider: 'v8',
  testEnvironment: 'node',
  roots: ['<rootDir>/apps/', '<rootDir>/libs/'],
  moduleNameMapper: {
    '^@app/shared(|/.*)$': '<rootDir>/libs/shared/src/$1',
    '^.+node_modules/\\.prisma/auth-client$': '<rootDir>/apps/auth/src/prisma/__mocks__/auth-client.js',
    '^@prisma-auth/client$': '<rootDir>/node_modules/.prisma/auth-client',
    '^@prisma-listing/client$': '<rootDir>/node_modules/.prisma/listing-client',
    '^@prisma-moderation/client$': '<rootDir>/node_modules/.prisma/moderation-client',
    '^@prisma-media/client$': '<rootDir>/node_modules/.prisma/media-client',
  },
  testTimeout: 30000,
  verbose: true,
  transformIgnorePatterns: ['/node_modules/(?!uuid/)'],
};
