# Exclure des fichiers de l’analyse
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/test/**,k8s/base/secrets-local.yaml

# Exclure de la couverture uniquement
sonar.coverage.exclusions=**/*.spec.ts,**/*.integration-spec.ts,**/test/**

# Exclure des tests de l’analyse (si on ne veut pas les analyser)
sonar.test.exclusions=**/*.spec.ts