# Réduire les replicas pour l'environnement local
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: cesi-shop
spec:
  replicas: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: listing-service
  namespace: cesi-shop
spec:
  replicas: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-service
  namespace: cesi-shop
spec:
  replicas: 1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moderation-service
  namespace: cesi-shop
spec:
  replicas: 1
