# Kustomization racine pour environnement local
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cesi-shop

resources:
  - base/namespace.yaml
  - base/configmap.yaml
  - base/secrets-local.yaml
  - infrastructure/postgresql-auth.yaml
  - infrastructure/postgresql-listing.yaml
  - infrastructure/postgresql-media.yaml
  - infrastructure/postgresql-moderation.yaml
  - infrastructure/rabbitmq.yaml
  - infrastructure/redis.yaml
  - infrastructure/minio.yaml
  - apps/frontend.yaml
  - apps/auth.yaml
  - apps/listing.yaml
  - apps/media.yaml
  - apps/moderation.yaml
  - base/ingress.yaml
  - base/ingress-minio.yaml
  # - jobs/migrate-all.yaml
  - jobs/seed-auth-job.yaml
  - jobs/seed-listing-job.yaml
  - jobs/seed-media-job.yaml
  - jobs/seed-moderation-job.yaml

# Patches pour l'environnement local
patches:
  - path: local/replicas-patch.yaml
  - path: local/resources-patch.yaml
  - path: local/image-pull-policy-patch.yaml

# Secret TLS pour HTTPS (nécessite make certs avant k8s-apply)
secretGenerator:
  - name: cesi-shop-tls
    type: kubernetes.io/tls
    files:
      - tls.crt=certs/cesi-shop.local.crt
      - tls.key=certs/cesi-shop.local.key
    options:
      disableNameSuffixHash: true

# Configuration pour le local
configMapGenerator:
  - name: local-config
    namespace: cesi-shop
    literals:
      - ENV=local
      - DEBUG=true

# Images (Minikube local)
images:
  - name: cesi-shop-frontend
    newName: cesi-shop-frontend
    newTag: dev
  - name: YOUR_REGISTRY/cesi-shop-auth
    newName: cesi-shop-auth
    newTag: dev
  - name: YOUR_REGISTRY/cesi-shop-listing
    newName: cesi-shop-listing
    newTag: dev
  - name: YOUR_REGISTRY/cesi-shop-media
    newName: cesi-shop-media
    newTag: dev
  - name: YOUR_REGISTRY/cesi-shop-moderation
    newName: cesi-shop-moderation
    newTag: dev
