# Secrets pour environnement local Minikube (NON SENSIBLES)
apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: cesi-shop
type: Opaque
stringData:
  POSTGRES_USER: cesishop_dev
  POSTGRES_PASSWORD: devpassword123
  AUTH_DATABASE_URL: postgresql://cesishop_dev:devpassword123@postgres-auth:5432/auth?schema=public
  LISTING_DATABASE_URL: postgresql://cesishop_dev:devpassword123@postgres-listing:5432/listing?schema=public
  MEDIA_DATABASE_URL: postgresql://cesishop_dev:devpassword123@postgres-media:5432/media?schema=public
  MODERATION_DATABASE_URL: postgresql://cesishop_dev:devpassword123@postgres-moderation:5432/moderation?schema=public
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
  namespace: cesi-shop
type: Opaque
stringData:
  JWT_SECRET: dev-jwt-secret-change-in-production-12345
  JWT_EXPIRES_IN: 24h
  JWT_PRIVATE_KEY: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC7VJTUt9Us8cKj
    MzEfYyjiWA4R4/M2bS1+fWIcPm15A9ra0ws7WeqL8CfXzC5pj7qFH7qQ8Lm3NwYB
    w3qj8dC0lKq7vKyKmPqSMvLPcqvGQbQXqvP0xOqHJdQnYlHX7gxJwlH4jvxsqGaA
    vKYGLqWpq8RaP0VnHqN8pQmZNNhpJ9z1KvKqF5vQ8XCKp0qLqYFHqXvP9xYHJqLj
    x8qQvD0xNqHJqLjx8qQvD0xNqHJqLjx8qQvD0xNqHJqLjx8qQvD0xNqHJqLjx8qQ
    vD0xNqHJqLjx8qQvD0xNqHJqLjx8qQvD0xNqHJqLjx8qQvD0xNqHJqLjx8qQvD0x
    AgMBAAECggEAXyClXjIoTvpQU8cH7p5rvvn0kQqE0X0jX/XqYp8qLZjJPqP7VYvQ
    5Lq8qQvD0xNqHJqLjx8qQvD0xNqHJqLjx8qQvD0xNqHJqLjx8qQvD0xNqHJqLjx8
    -----END PRIVATE KEY-----
  JWT_PUBLIC_KEY: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAu1SU1LfVLPHCozMxH2Mo
    4lgOEePzNm0tfn1iHD5teQPa2tMLO1nqi/An18wuaY+6hR+6kPC5tzcGAcN6o/HQ
    tJSqu7ysipj6kjLyz3KrxkG0F6rz9MTqhyXUJ2JR1+4MScJR+I78bKhmgLymBi6l
    qavEWj9FZx6jfKUJmTTYaSfc9SryqhebNm0tfn1iHD5teQPa2tMLO1nqi/An18wu
    -----END PUBLIC KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secrets
  namespace: cesi-shop
type: Opaque
stringData:
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_PASSWORD: devredis123
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secrets
  namespace: cesi-shop
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: rabbit_dev
  RABBITMQ_DEFAULT_PASS: devrabbit123
  RABBITMQ_URL: amqp://rabbit_dev:devrabbit123@rabbitmq:5672/
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secrets
  namespace: cesi-shop
type: Opaque
stringData:
  MINIO_ROOT_USER: minio_dev
  MINIO_ROOT_PASSWORD: devminio123
  MINIO_ENDPOINT: minio
  MINIO_PORT: "9000"
  MINIO_USE_SSL: "false"
  MINIO_ACCESS_KEY: minio_dev
  MINIO_SECRET_KEY: devminio123
